version: '2'
services:
    cs499assignment2-mysql:
        container_name: cs499assignment2-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/cs499assignment2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=cs499assignment2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
