# ===================================================================
# Spring Boot configuration.
#
# This configuration is used for unit/integration tests.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    application:
        name: cs499assignment2
    jackson:
        serialization.write_dates_as_timestamps: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:cs499assignment2;DB_CLOSE_DELAY=-1
        name:
        username:
        password:
    jpa:
        database-platform: com.cs499.a2.domain.util.FixedH2Dialect
        database: H2
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate
    mail:
        host: localhost
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

liquibase:
    contexts: test

security:
    basic:
        enabled: false

server:
    port: 10344
    address: localhost

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: dfafc71ca07f9bb7f0253d03a9850d96de97fedc
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
    swagger:
        title: cs499assignment2 API
        description: cs499assignment2 API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
